#Minecraft server properties
#Fri Mar 26 23:08:26 BRT 2021
view-distance=4
max-build-height=256
server-ip=0.0.0.0
level-seed=
allow-nether=false
gamemode=0
enable-command-block=false
server-port=26133
enable-rcon=false
server-name=Unknown Server
enable-query=false
op-permission-level=4
generator-settings=
resource-pack=
player-idle-timeout=0
level-name=world
motd=A Minecraft Server
announce-player-achievements=false
force-gamemode=false
debug=false
hardcore=false
white-list=true
broadcast-console-to-ops=true
pvp=true
spawn-npcs=true
spawn-animals=true
generate-structures=false
snooper-enabled=false
difficulty=1
network-compression-threshold=512
level-type=DEFAULT
spawn-monsters=true
max-players=2020
use-native-transport=true
spawn-protection=16
online-mode=false
allow-flight=false
resource-pack-hash=
max-world-size=29999984
